{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $metas = ezini('Settings', 'Metas', 'novaseo.ini')}
<div class="block novaseao-metas">
    <div class="">
        <ul>
            {foreach $metas as $meta }
                <li>
                    <label>{$meta.label|wash}:</label> {if and(is_set($attribute.content.metas),is_set($attribute.content.metas[$meta.key]))}{$attribute.content.metas[$meta.key].content|wash}{/if}
                </li>
            {/foreach}
        </ul>
    </div>
</div>

