{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if is_set( $attribute_base )|not}
    {def $attribute_base = 'ContentObjectAttribute'}
{/if}

{def $metas = ezini('Settings', 'Metas', 'novaseo.ini')}
<div class="block novaseao-metas">
    <div class="element">
        {foreach $metas as $meta }
            <p>
                <label for="{$attribute_base}_data_novaseometas_{$attribute.contentclass_attribute_identifier}_keyvalue_{$attribute.id}">{$meta.label|wash}</label>
                <input
                        type="text"
                        id="{$attribute_base}_data_novaseometas_{$attribute.contentclass_attribute_identifier}_keyvalue_{$attribute.id}"
                        name="{$attribute_base}_data_novaseometas_{$attribute.contentclass_attribute_identifier}_keyvalue_{$attribute.id}[{$meta.key|wash}]"
                        value="{if and(is_set($attribute.content.metas),is_set($attribute.content.metas[$meta.key]))}{$attribute.content.metas[$meta.key].content|wash}{/if}"
                        />
            </p>
        {/foreach}
    </div>
    <div class="break"></div>
</div>

{undef $metas}