{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $metas = ezini('Settings', 'Metas', 'novaseo.ini')}

<div class="block novaseao-metas novaseao-metas-class-edit">
    <div class="">
        <ul>
            {foreach $metas as $key => $meta }
                <li class="meta">
                    <label for="ContentClass_novaseometas_keyvalue_{$class_attribute.id}"><i class="fa fa-{$meta.icon}"></i> {$meta.label|wash}</label>
                    <input
                            type="text"
                            id="ContentClass_novaseometas_keyvalue_{$class_attribute.id}"
                            name="ContentClass_novaseometas_keyvalue_{$class_attribute.id}[{$key|wash}]"
                            value="{if is_set($class_attribute.content[$key])}{$class_attribute.content[$key]|wash}{/if}"
                            />
                    <div class="break"></div>
                    <ul class="default_values">
                        {if is_set($meta['default_pattern'])}
                            <li><label>Settings: </label>&nbsp;{$metas[$key].default_pattern|wash}</li>
                        {/if}
                    </ul>
                </li>
            {/foreach}
        </ul>
        {include uri="design:novaseometas_providedby.tpl"}
    </div>
    <div class="break"></div>
</div>
{undef $metas}