{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $metas = ezini('Settings', 'Metas', 'novaseo.ini')}

<div class="block novaseao-metas">
    <div class="">
        <ul>
            {foreach $metas as $key => $meta }
                <li>
                    <label for="ContentClass_novaseometas_keyvalue_{$class_attribute.id}">{$meta.label|wash}</label>
                    <input
                            type="text"
                            id="ContentClass_novaseometas_keyvalue_{$class_attribute.id}"
                            name="ContentClass_novaseometas_keyvalue_{$class_attribute.id}[{$key|wash}]"
                            value="{if is_set($class_attribute.content[$key])}{$class_attribute.content[$key]|wash}{/if}"
                            />
                </li>
            {/foreach}
        </ul>
        {include uri="design:novaseometas_providedby.tpl"}
    </div>
    <div class="break"></div>
</div>
{undef $metas}