{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $metas = ezini('Settings', 'Metas', 'novaseo.ini')}
<div class="block novaseao-metas">
    <div class="">
        <ul>
            {foreach $metas as $key => $meta }
                <li>
                    <label>{$meta.label|wash}:</label>&nbsp;{if is_set($class_attribute.content[$key])}{$class_attribute.content[$key]|wash}{/if}
                </li>
            {/foreach}
        </ul>
    </div>
</div>

